//This file is generated by bin/hook.js
var _ = require('underscore');
module.exports = {

  'level_selector': _.template('<button data-level-selector-button>  Auto</button><ul>  <li><a href="#" data-level-selector-select="-1">AUTO</a></li>  <% for (var i = 0; i < levels.length; i++) { %>    <li><a href="#" data-level-selector-select="<%= i %>"><%= Math.floor(levels[i].bitrate / 1000) %>kbps</a></li>  <% }; %></ul>'),

  CSS: {
    
      'level_selector': '.level_selector[data-level-selector]{font-smooth:never;-webkit-font-smoothing:none;float:right;margin-top:5px;position:relative}.level_selector[data-level-selector] button{background-color:transparent;color:#fff;font-family:Roboto,"Open Sans",Arial,sans-serif;border:none;font-size:10px}.level_selector[data-level-selector] button:hover{color:#c9c9c9}.level_selector[data-level-selector] button.changing{-webkit-animation:pulse .5s infinite alternate}.level_selector[data-level-selector]>ul{list-style-type:none;position:absolute;bottom:25px;border:1px solid #000;display:none;background-color:#e6e6e6}.level_selector[data-level-selector] li a{color:#444;padding:2px 10px;display:block;text-decoration:none;font-size:10px}.level_selector[data-level-selector] li:hover{background-color:#555;color:#fff}.level_selector[data-level-selector] li:hover a{color:#fff;text-decoration:none}@-webkit-keyframes pulse{0%{color:#fff}50%{color:#ff0101}100%{color:#B80000}}',
    
  }
};
